name: Demo workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: statement 1
        run: echo Hello, world!
      - name: statement 2
        run: |
          echo test your workflow,
          echo test, and deploy your project.
      - name: install java     
        uses: actions/setup-java@v4
        with: 
          java-version: "11"
      - name: test java version
        run: java --version

     
     
